language: java
jdk:
  - openjdk11
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
before_install:
  - chmod +x mvnw

services:
  - postgresql

before_script:
  - sudo psql -c 'CREATE DATABASE amazon;' -U postgres

script:
  - mvn clean install
